### ISSUE TITLE
Fields ignored when tag `json:"-"` along with storm tags is present - even if I use protobuf

### ISSUE THREAD

**Issue by turbopape** [asdine/storm#113] opened 2016-10-25 15:18 UTC
Hey guys,

I am using a record struct to persist in a Bolt DB via storm AND to marshal it into JSON so I can send it over a POST http REST request.

I have an ID field that I want auto-incremented, and I don't want to send it over the REST API, so I defined it like so:
...
	ID            string `storm:"increment" json:"-"`
I found that this field is not persisted into the DB.
I thought it was becaus we use json encoding by default. So I switched to protobuf, and the result is the same.

Thank you for your assistance, and keep on the great work guys !

Cheers

**Comment by asdine** [comment] 2016-10-25 18:00
This is indeed the intended behavior. You should simply use another struct as your "response" and copy the fields from the one used to save a record, it would allow you to decouple your model from its representation.

**Comment by turbopape** [comment] 2016-10-25 18:32
Ah thank you!

I actually found it interesting to use uuid and to send that over to the
REST api, but l get your point!

Great lib guys. I just discovered q and loving it!

Keep on rocking!

Rafij

Le 25 oct. 2016 19:00, "Asdine El Hrychy" <notifications@github.com> a
écrit :

**Comment by asdine** [comment] 2016-10-25 18:35
Thank you for you comment 👍 ! I'm closing this issue, don't hesitate if you have another question :)

**Closed by asdine** 2016-10-25 18:35 UTC
Labels: question
