### ISSUE TITLE
Storm is really slow

### ISSUE THREAD

**Issue by 89z** [asdine/storm#284] opened 2020-12-30 23:43 UTC
Storm looks interesting to me, as I am currently using SQLite for a small
project, and I like that Storm can hold different types of data. My SQL schema
looks something like this:

~~~sql
create table artist_t (
   artist_n integer primary key,
   artist_s text,
);
create table album_t (
   album_n integer primary key,
   album_s text,
);
create table song_t (
   song_n integer primary key,
   song_s text,
   album_n integer
);
create table song_artist_t (
   song_n integer,
   artist_n integer
);
~~~

so I made a similar model with Storm like this:

~~~go
type Artist struct {
   ID int `storm:"increment"`
   Name string
   Album []int
}
type Album struct {
   ID int `storm:"increment"`
   Name string
   Song []int
}
type Song struct {
   ID int `storm:"increment"`
   Name string
}
~~~

but I noticed that just doing a loop similar to this:

~~~go
for _, album_n := range artist_o.Album {
   album_o := Album{}
   tx.One("ID", album_n, &album_o)
   for _, song_n := range album_o.Song {
      song_o := Song{}
      tx.One("ID", song_n, &song_o)
      fmt.Println(song_o)
   }
}
~~~

The speed was shockingly bad with Storm. With SQLite I got this:

~~~
TotalMilliseconds : 13.7533
~~~

and with Storm I got this:

~~~
TotalMilliseconds : 4173.8005
~~~

I thought maybe it had to do with using the DB object directly, but I tried it
again using a transaction and it seemed to be the same speed. Am I doing something
wrong here, or is that just the nature of this package? I can link to my actual
code if need be, or provide my database files.

**Comment by 89z** [comment] 2020-12-31 00:09
https://github.com/schollz/find3/issues/39

**Comment by asdine** [comment] 2020-12-31 06:42
Storm is currently not optimized because of how it was designed initially. I am currently working on another database called Genji (https://github.com/genjidb/genji), which is a document oriented embedded SQL database. It is designed to be really fast, (though I haven't optimized it yet)
The next version of Storm will probably use it under the hood but it won't happen until Genji's API becomes stable.

**Comment by 89z** [comment] 2020-12-31 23:53
Ok Genji does seem to be much faster:

~~~
TotalMilliseconds : 882.0847
~~~

but its still a pretty big difference from SQLite. I used code similar to below.
If I am missing some optimization let me know, thanks!

~~~go
d, e := tx.QueryDocument("SELECT album from artist_t where id = 124")
if e != nil {
   return e
}
album_a := []int{}
document.Scan(d, &album_a)
for _, album_n := range album_a {
   d, e = tx.QueryDocument("SELECT song from album_t where id = ?", album_n)
   if e != nil {
      return e
   }
   song_a := []int{}
   document.Scan(d, &song_a)
   for _, song_n := range song_a {
      d, e = tx.QueryDocument("SELECT name from song_t where id = ?", song_n)
      if e != nil {
         return e
      }
      var name string
      document.Scan(d, &name)
      fmt.Println(name)
   }
}
~~~

**Comment by asdine** [comment] 2021-01-01 07:07
I suppose `id` is your primary key? If so, there is a [bug ](https://github.com/genjidb/genji/issues/310) that I'm working on (Genji is still a work in progress) that prevents using the fast path for indexes. It will be fixed in the v0.10

Try this:

```sql
CREATE TABLE artist_t(id INT); -- don't make ID the primary key

CREATE UNIQUE INDEX idx_artist_t_id ON artist_t(id);
```

This should use the index and have a better performance.

**Comment by 89z** [comment] 2021-01-01 15:31
Whoa that made a huge difference!

~~~
TotalMilliseconds : 86.4374
~~~

I only did Index on the Album and Song though, as they are the ones in the loop.
Its still slower than SQLite, but its close enough that I think the trade off is
probably worth it. I like the idea of not having to have junction tables.

Thank you!

**Comment by asdine** [comment] 2021-01-01 15:34
There is still no optimization done, I believe there is room for a lot of improvement (though I'm not sure it will ever get faster than SQLite). This will be done once the project is more mature and the API stable.

**Comment by 89z** [comment] 2021-01-01 15:37
The ability to have Slice values is huge in my opinion. It makes the whole database layout simpler, and you dont need junction tables, and in my case you dont have to worry about doing table Joins. So anything that offers that, and can get somewhat decent speed (which Genji has with Index) is a win in my book. Speed is important, but its not the only factor.

**Closed** 2021-01-01 19:33 UTC
